### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by Dforssi** [gotonode/compress#3]
**Project downloaded as ZIP: 13.2.2019 at around 13:00.**

First of all, I would like to congratulate you on doing such an exemplary project. Your documentation is well written and comprehensive which makes it a joy to peer review and dive into your code. Code quality is up to Java standards and easy to read. In fact, the overall level of your project is high enough to leave almost no room for constructive feedback, and I had to really comb through your classes to find things I might improve on.

The main thing that struck me as something that you could perhaps improve on is **commenting** your code in a consistent way. It seems that some classes have extensive commentary, and others are more... self documenting. Some classes, like _App.java_ and _Main.java_, have comments that I would consider redundant, like commenting a Scanner object with //Where to read user input from. I would consider a Scanner such a basic object that it requires no further comments. _Main.java_ also has multiple line, extensive commentary for basic variables, but _App.java_ and _Benchmark.java_ have methods with 100ish lines of uncommented code. You could look into unifying the commenting style between classes. You could also consider refactoring some multiple line comments into javadoc comments, as they clearly are important enough to have extensive commentary.

It could also be good to have a short introduction to the two algorithms in your readme file. Just a few sentences and some key points in how they work and how they differ, before linking to their respective wikipedia pages. This would give me as a reader a better look into what is going on without having to scan through wikipedia links.

Overall you've done an excellent job!

**Comment by gotonode** [comment]
Thank you for the peer review. Comments like these are indeed spirit-lifting. I've been coding since early elementary school and glad it shows.

I wish our courses would have more peer reviews in them, since code comprehension is a major part of our job.

Your suggestions have been taken into consideration and I do agree with them. I haven't finished commenting everything, especially the LZW algorithm. I also agree that commenting what a Scanner does is redundant but because part of our grade comes from how well we comment our code I didn't want to leave anything to chance.

I'll also add descriptions of the algorithms on the main page. After all, these repositories serve as our CV.

Good luck on your project!

**Comment by gotonode** [comment]
Issue closed. Peer review grade A.
